In [22]:
import pandas as pd
import numpy as np

In [75]:
templates = pd.read_json("templates.json")
init_uttr_updated = pd.read_csv("InitUtterance_list_updated.csv")
templates_updated = templates.merge(init_uttr_updated, on='id')
templates_updated = templates_updated[['id','de', 'fr', 'it', 'en']]
templates_updated.head()

,id,de,fr,it,en
0,MyCloud.OpenArea.Init.Utterance,{'texts': [{'ttsText': '{MyCloudArea} auf #myC...,{'texts': [{'ttsText': 'afficher {MyCloudArea}...,{'texts': [{'ttsText': 'apri {MyCloudArea} su ...,{'texts': [{'ttsText': 'show {MyCloudArea} on ...
1,Router.SwitchOnWiFi.Init.Utterance,"{'texts': [{'ttsText': 'aktiviere das Wlan'}, ...","{'texts': [{'ttsText': 'active le Wi-Fi'}, {'t...","{'texts': [{'ttsText': 'attiva il #wifi'}, {'t...","{'texts': [{'ttsText': 'activate the Wi-Fi'}, ..."
2,Tv.GenericExitToTv.Init.Utterance,{'texts': [{'ttsText': 'gehe zurück zum Fernse...,"{'texts': [{'ttsText': 'revenir à la télé'}, {...","{'texts': [{'ttsText': 'torna alla TV'}, {'tts...","{'texts': [{'ttsText': 'back to TV'}, {'ttsTex..."
3,Router.SwitchOffWiFi.Init.Utterance,{'texts': [{'ttsText': 'deaktiviere das Wlan'}...,"{'texts': [{'ttsText': 'désactiver le Wi-Fi'},...","{'texts': [{'ttsText': 'disattiva il wifi'}, {...",{'texts': [{'ttsText': 'can you please switch ...
4,Tv.RadioChannelChange.Init.Utterance,{'texts': [{'ttsText': 'auf Radio {RadioChanne...,{'texts': [{'ttsText': 'prendre radio {RadioCh...,{'texts': [{'ttsText': 'metti radio {RadioChan...,{'texts': [{'ttsText': 'can you turn on radio ...

In [74]:
entities = pd.read_json("entities.json")
entities = entities[['value', 'type', 'language', 'normalizedValue']]
entities.head()

       value                 type language normalizedValue
0     Widnau  LocalsearchLocation       de          widnau
1     Zurigo  LocalsearchLocation       it          zurigo
2  Solothurn  LocalsearchLocation       de       solothurn
3    Muttenz  LocalsearchLocation       de         muttenz
4       Lyss  LocalsearchLocation       de            lyss

In [72]:
templates_updated['de'][0]['texts'][0]['ttsText']

'{MyCloudArea} auf #myCloud anzeigen'

In [77]:
entities[entities['value'].str.contains('1')]

,value,type,language,normalizedValue
8969,391,ArtistName,en,three hundred and ninety one
8971,100 blaze,ArtistName,en,one hundred blaze
8979,21 pilots,ArtistName,en,twenty one pilots
8997,18 karat,ArtistName,en,eighteen karat
9013,21 savage,ArtistName,en,twenty one savage
...,...,...,...,...
65245,Night stand 1,SmartHomeDeviceName,en,night stand one
65246,entrata 1,SmartHomeDeviceName,it,entrata uno
65255,hue color candle 1,SmartHomeDeviceName,fr,hue color candle un
65260,Hue color light 1,SmartHomeDeviceName,fr,hue color light un
65426,1,SmartHomeSceneName,fr,un

In [62]:
from essential_generators import DocumentGenerator

In [67]:
gen = DocumentGenerator()

MyCloudArea = {'{} auf #myCloud anzeigen'
}

gen.set_template(template)
documents = gen.documents(10)

In [78]:
entities

              value                 type language normalizedValue
0            Widnau  LocalsearchLocation       de          widnau
1            Zurigo  LocalsearchLocation       it          zurigo
2         Solothurn  LocalsearchLocation       de       solothurn
3           Muttenz  LocalsearchLocation       de         muttenz
4              Lyss  LocalsearchLocation       de            lyss
...             ...                  ...      ...             ...
65466    baby dance   SmartHomeSceneName       en      baby dance
65467     Fernseher   SmartHomeSceneName       de       fernseher
65468  tutto spento   SmartHomeSceneName       it    tutto spento
65469     lumières    SmartHomeSceneName       fr        lumières
65470           zen   SmartHomeSceneName       en             zen

[65471 rows x 4 columns]